name: Company Website

on:

  push:

    branches:

      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Build Docker Image

      run: docker build -t company-website .

    - name: Success

      run: echo "Build Successful"